function Precache() {
	self.PrecacheSoundScript("sound/bee2/p1/pgun/ambient.wav")
	self.PrecacheSoundScript("sound/bee2/p1/pgun/portal_enter1.wav")
	self.PrecacheSoundScript("sound/bee2/p1/pgun/portal_enter2.wav")
	self.PrecacheSoundScript("sound/bee2/p1/pgun/portal_exit1.wav")
	self.PrecacheSoundScript("sound/bee2/p1/pgun/portal_exit2.wav")
	self.PrecacheSoundScript("sound/physics/metal/metal_box_scrape_rough_loop1.wav")
	self.PrecacheSoundScript("sound/physics/metal/metal_box_scrape_smooth_loop1.wav")
	self.PrecacheSoundScript("sound/player/footsteps/concrete1.wav")
	self.PrecacheSoundScript("sound/player/footsteps/concrete2.wav")
	self.PrecacheSoundScript("sound/player/footsteps/concrete3.wav")
	self.PrecacheSoundScript("sound/player/footsteps/concrete4.wav")
	self.PrecacheSoundScript("sound/player/footsteps/metal1.wav")
	self.PrecacheSoundScript("sound/player/footsteps/metal2.wav")
	self.PrecacheSoundScript("sound/player/footsteps/metal3.wav")
	self.PrecacheSoundScript("sound/player/footsteps/metal4.wav")
}
